### ISSUE TITLE
Authorization headers defined in graphiql does not work

### ISSUE THREAD

**Issue by mjd507** [graphql-java/graphql-spring-boot#111]
I upgrade `graphql-spring-boot-starter` & `graphiql-spring-boot-starter` to version 5.0.2, and follow README to config a graphiql with headers，but I can't see the custom header `Authorization` in the request header. is anything wrong?
```yml
graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true
  headers:
    Authorization: "Bearer  05bd9a5f3fe0408f89520946b0fe1b06"

```

**Comment by oliemansm** [comment]
It's added to the headers of the requests sent by GraphiQL. I just tested it again with this configuration:
```yaml
graphiql:
  headers:
    Authorization: "Bearer 05bd9a5f3fe0408f89520946b0fe1b06"
```
Which resulted in the header correctly being added to the request:
![image](https://user-images.githubusercontent.com/13518144/44615538-95d3f400-a83c-11e8-8a26-4afe50d0c603.png)
