### ISSUE TITLE
Graphiql behind a proxy is not working

### ISSUE THREAD

**Issue by ccamel** [graphql-java/graphql-spring-boot#117]
As a consequence of #83, graphiql seems to be no more able to access the vendor resources nor the subscriptions when  behind a proxy.

For instance, one of our service is configured as such:
```yaml
graphiql:
      mapping: /graphiql
      endpoint: /my-service/graphql
      enabled: true
```

The service is deployed through the proxy with the route `http://foo.bar/my-service/`. So it exposes the following endpoints:
- graphiql: `http://foo.bar/my-service/graphiql`
- graphql: `http://foo.bar/my-service/graphql`
- subscriptions: `http://foo.bar/my-service/subscriptions`

In that case, the resources retrieved by the browser are:
- ✅ 200: `http://foo.bar/my-service/graphiql`
- ❌ 404: `http://foo.bar/vendor/es6-promise.auto.min.js`
- ❌ 404: `http://foo.bar/vendor/fetch.min.js`
- ❌ 404: `http://foo.bar/vendor/react.min.js`
- ...
- ❌ 404: `http://foo.bar/subscriptions`
